In [21]:
import os
import glob
import re
import pandas as pd
import torch

from transformers import AutoTokenizer, AutoModelForCausalLM
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score

torch.backends.cuda.matmul.allow_tf32 = True
torch.set_float32_matmul_precision("high")

print("Libraries imported successfully!")

Libraries imported successfully!

In [28]:
tsv_files = glob.glob("/kaggle/input/**/*.tsv", recursive=True)

print("TSV files found:")
for file in tsv_files:
    print(file)

if not tsv_files:
    raise FileNotFoundError("No TSV file found inside /kaggle/input/")

DATA_PATH = tsv_files[0]

print("\nUsing dataset:")
print(DATA_PATH)

TSV files found:
/kaggle/input/datasets/robinhossain231/microsoft/blp23_sentiment_dev.tsv

Using dataset:
/kaggle/input/datasets/robinhossain231/microsoft/blp23_sentiment_dev.tsv

In [29]:
df = pd.read_csv(DATA_PATH, sep="\t")

print("Dataset loaded successfully!")
print("\nShape:")
print(df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

Dataset loaded successfully!

Shape:
(3934, 3)

Columns:
['id', 'text', 'label']

      id                                               text     label
0   5300  নতুন মতলব আটছে । মানে সৌদি আরব ধ্বংস করার পায়ত...  Negative
1  15392  বিদেশে পড়ালেখা করছে বাংলাদেশের প্রচুর ছেলেময়ের...  Positive
2   6904  মাননীয় আপনি নিজে না বলে সস্তায় কোনো মন্ত্রী কে...  Negative
3  30790   * করোনার টিকা নিলেন বিএনপি চেয়ারপারসন বেগম খ...  Positive
4   2770  একজন প্রধানমন্ত্রীর এমন বক্তব্য জাতির জন্য লজ্...  Negative

In [30]:
TEXT_COLUMN = "text"
LABEL_COLUMN = "label"

sentiment_df = df[["id", TEXT_COLUMN, LABEL_COLUMN]].copy()
sentiment_df["text"] = sentiment_df["text"].astype(str)
sentiment_df["label"] = sentiment_df["label"].astype(str).str.strip()

print("Dataset prepared successfully!")
print("\nShape:")
print(sentiment_df.shape)
print("\nColumns:")
print(sentiment_df.columns.tolist())

display(sentiment_df.head())

Dataset prepared successfully!

Shape:
(3934, 3)

Columns:
['id', 'text', 'label']

      id                                               text     label
0   5300  নতুন মতলব আটছে । মানে সৌদি আরব ধ্বংস করার পায়ত...  Negative
1  15392  বিদেশে পড়ালেখা করছে বাংলাদেশের প্রচুর ছেলেময়ের...  Positive
2   6904  মাননীয় আপনি নিজে না বলে সস্তায় কোনো মন্ত্রী কে...  Negative
3  30790   * করোনার টিকা নিলেন বিএনপি চেয়ারপারসন বেগম খ...  Positive
4   2770  একজন প্রধানমন্ত্রীর এমন বক্তব্য জাতির জন্য লজ্...  Negative

In [31]:
!pip uninstall -y huggingface_hub
!pip install --no-cache-dir "huggingface_hub>=1.3.0,<2.0"

Found existing installation: huggingface_hub 1.11.0
Uninstalling huggingface_hub-1.11.0:
  Successfully uninstalled huggingface_hub-1.11.0
Collecting huggingface_hub<2.0,>=1.3.0
  Downloading huggingface_hub-1.33.0-py3-none-any.whl.metadata (16 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface_hub<2.0,>=1.3.0)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<2.0,>=1.3.0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<2.0,>=1.3.0) (2025.3.0)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface_hub<2.0,>=1.3.0)
  Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<2.0,>=1.3.0) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<2.0,>=1.3.0) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<2.0,>=1.3.0) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<2.0,>=1.3.0) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<2.0,>=1.3.0) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub<2.0,>=1.3.0) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub<2.0,>=1.3.0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub<2.0,>=1.3.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub<2.0,>=1.3.0) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub<2.0,>=1.3.0) (0.16.0)
Downloading huggingface_hub-1.33.0-py3-none-any.whl (846 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 846.4/846.4 kB 15.6 MB/s eta 0:00:00 0:00:01
Downloading click-8.5.0-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.3/125.3 kB 213.2 MB/s eta 0:00:00
Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 145.3 MB/s eta 0:00:00
Installing collected packages: hf-xet, click, huggingface_hub
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.4.3
    Uninstalling hf-xet-1.4.3:
      Successfully uninstalled hf-xet-1.4.3
  Attempting uninstall: click
    Found existing installation: click 8.3.3
    Uninstalling click-8.3.3:
      Successfully uninstalled click-8.3.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
Successfully installed click-8.5.0 hf-xet-1.6.0 huggingface_hub-1.33.0

In [32]:
import huggingface_hub

print(huggingface_hub.__version__)

1.11.0

In [33]:
from huggingface_hub import login

HF_TOKEN = "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"

login(token=HF_TOKEN)

In [34]:
MODEL_NAME = "meta-llama/Llama-3.2-3B-Instruct"

dtype = torch.bfloat16 if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float16

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=dtype,
    device_map="auto",
    low_cpu_mem_usage=True
)

model.eval()

print("Model loaded successfully!")

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

Model loaded successfully!

In [35]:
def generate_response(prompt, max_new_tokens=10):
    messages = [{"role": "user", "content": prompt}]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt",
        truncation=True,
        max_length=2048
    )

    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            num_beams=1,
            use_cache=True,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )

    generated_tokens = outputs[:, inputs["input_ids"].shape[1]:]
    response = tokenizer.batch_decode(
        generated_tokens,
        skip_special_tokens=True
    )[0].strip()

    return response

In [36]:
def extract_label(response):
    text = response.strip()

    match = re.search(
        r"final\s*(?:sentiment\s*)?label\s*:\s*(positive|negative|neutral)",
        text,
        re.IGNORECASE
    )

    if match:
        return match.group(1).capitalize()

    matches = re.findall(
        r"\b(positive|negative|neutral)\b",
        text,
        re.IGNORECASE
    )

    if matches:
        return matches[-1].capitalize()

    return "Unknown"

In [14]:
def zero_shot_prompt(text):
    return f"""You are a Bengali sentiment analysis model.

Analyze the sentiment of the following Bengali text.

Text:
{text}

Classify the sentiment as one of:
Positive
Negative
Neutral

Return only one word: Positive, Negative, or Neutral."""

In [15]:
test_text = sentiment_df.iloc[0]["text"]

response = generate_response(
    zero_shot_prompt(test_text),
    max_new_tokens=10
)

prediction = extract_label(response)

print("Text:")
print(test_text)
print("\nModel Response:")
print(response)
print("\nPredicted Sentiment:")
print(prediction)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Text:
নতুন মতলব আটছে । মানে সৌদি আরব ধ্বংস করার পায়তারা শুরু করছে ।

Model Response:
Negative

Predicted Sentiment:
Negative

In [16]:
zero_shot_predictions = []

for i, text in enumerate(sentiment_df["text"]):
    response = generate_response(
        zero_shot_prompt(text),
        max_new_tokens=10
    )

    zero_shot_predictions.append(extract_label(response))

    if (i + 1) % 100 == 0:
        print(f"Processed {i + 1}/{len(sentiment_df)}")

sentiment_df["zero_shot_prediction"] = zero_shot_predictions

Processed 100/3934
Processed 200/3934
Processed 300/3934
Processed 400/3934
Processed 500/3934
Processed 600/3934
Processed 700/3934
Processed 800/3934
Processed 900/3934
Processed 1000/3934
Processed 1100/3934
Processed 1200/3934
Processed 1300/3934
Processed 1400/3934
Processed 1500/3934
Processed 1600/3934
Processed 1700/3934
Processed 1800/3934
Processed 1900/3934
Processed 2000/3934
Processed 2100/3934
Processed 2200/3934
Processed 2300/3934
Processed 2400/3934
Processed 2500/3934
Processed 2600/3934
Processed 2700/3934
Processed 2800/3934
Processed 2900/3934
Processed 3000/3934
Processed 3100/3934
Processed 3200/3934
Processed 3300/3934
Processed 3400/3934
Processed 3500/3934
Processed 3600/3934
Processed 3700/3934
Processed 3800/3934
Processed 3900/3934

In [17]:
display(
    sentiment_df[
        ["id", "text", "label", "zero_shot_prediction"]
    ].head(10)
)

,id,text,label,zero_shot_prediction
0,5300,নতুন মতলব আটছে । মানে সৌদি আরব ধ্বংস করার পায়ত...,Negative,Negative
1,15392,বিদেশে পড়ালেখা করছে বাংলাদেশের প্রচুর ছেলেময়ের...,Positive,Positive
2,6904,মাননীয় আপনি নিজে না বলে সস্তায় কোনো মন্ত্রী কে...,Negative,Negative
3,30790,* করোনার টিকা নিলেন বিএনপি চেয়ারপারসন বেগম খ...,Positive,Positive
4,2770,একজন প্রধানমন্ত্রীর এমন বক্তব্য জাতির জন্য লজ্...,Negative,Negative
5,15617,শিক্ষক দের মান উন্নয়নে ও কাজ করতে হবে,Positive,Positive
6,11628,চোর বেশি তাই,Negative,Negative
7,sentinob_1080,"হাহাহাহা , না আপনার ভয়ের কোন কারণ নেই । সবগুলো...",Neutral,Positive
8,27109,সেসময় একটু বেছে নিতে হবে আপনার সময় ও পছন্দ অ...,Neutral,Neutral
9,30142,সম্মেলন আয়োজনকে ঘিরে হেফাজতে ইসলামের নেতৃত্বে...,Negative,Negative

In [19]:
y_true = sentiment_df["label"].str.lower().str.strip()
y_pred = sentiment_df["zero_shot_prediction"].str.lower().str.strip()

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)
kappa = cohen_kappa_score(y_true, y_pred)

print("Llamma Zero-Shot Results")
print("----------------------------")
print(f"Accuracy   : {accuracy:.4f}")
print(f"Precision  : {precision:.4f}")
print(f"Recall     : {recall:.4f}")
print(f"F1-Score   : {f1:.4f}")
print(f"Cohen Kappa: {kappa:.4f}")

Llamma Zero-Shot Results
----------------------------
Accuracy   : 0.5676
Precision  : 0.5800
Recall     : 0.5676
F1-Score   : 0.5485
Cohen Kappa: 0.2959

In [20]:
def few_shot_prompt(text):
    return f"""You are a Bengali sentiment analysis model.

Use the following labeled examples to understand the sentiment classification task.

Example 1:
Text: এই পণ্যটি খুব ভালো এবং আমি এটি পছন্দ করেছি।
Sentiment: Positive

Example 2:
Text: সেবাটি খুব খারাপ, আমি একদম সন্তুষ্ট নই।
Sentiment: Negative

Example 3:
Text: পণ্যটি মোটামুটি, বিশেষ ভালো বা খারাপ কিছু নয়।
Sentiment: Neutral

Now classify the sentiment of the following Bengali text.

Text:
{text}

Choose exactly one:
Positive
Negative
Neutral

Return only the sentiment label."""

In [ ]:
few_shot_predictions = []

for i, text in enumerate(sentiment_df["text"]):
    response = generate_response(
        few_shot_prompt(text),
        max_new_tokens=10
    )

    few_shot_predictions.append(extract_label(response))

    if (i + 1) % 100 == 0:
        print(f"Processed {i + 1}/{len(sentiment_df)}")

sentiment_df["few_shot_prediction"] = few_shot_predictions

print("Few-Shot prediction completed.")

Processed 100/3934
Processed 200/3934
Processed 300/3934
Processed 400/3934
Processed 500/3934
Processed 600/3934
Processed 700/3934
Processed 800/3934
Processed 900/3934
Processed 1000/3934
Processed 1100/3934

In [ ]:
y_true = sentiment_df["label"].str.lower().str.strip()
y_pred = sentiment_df["few_shot_prediction"].str.lower().str.strip()

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)
kappa = cohen_kappa_score(y_true, y_pred)

print("Few-Shot Results")
print("----------------------------")
print(f"Accuracy   : {accuracy:.4f}")
print(f"Precision  : {precision:.4f}")
print(f"Recall     : {recall:.4f}")
print(f"F1-Score   : {f1:.4f}")
print(f"Cohen Kappa: {kappa:.4f}")

In [37]:
def cot_prompt(text):
    return f"""You are a Bengali sentiment analysis model.

Your task is to classify the sentiment of the given Bengali text into exactly one of these three categories:

Positive
Negative
Neutral

Think step by step before making the final decision.

Follow these steps:
1. Understand the meaning of the Bengali text.
2. Identify the main opinion or emotion expressed in the text.
3. Determine whether the expressed sentiment is positive, negative, or neutral.
4. Consider the overall context and tone of the text.
5. Select the most appropriate sentiment label.

Text:
{text}

After completing your analysis, provide ONLY the final sentiment label:
Positive
Negative
Neutral"""

In [38]:
cot_predictions = []

for i, text in enumerate(sentiment_df["text"]):
    response = generate_response(
        cot_prompt(text),
        max_new_tokens=10
    )

    cot_predictions.append(extract_label(response))

    if (i + 1) % 100 == 0:
        print(f"Processed {i + 1}/{len(sentiment_df)}")

sentiment_df["cot_prediction"] = cot_predictions

print("CoT prediction completed.")

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Processed 100/3934
Processed 200/3934
Processed 300/3934
Processed 400/3934
Processed 500/3934
Processed 600/3934
Processed 700/3934
Processed 800/3934
Processed 900/3934
Processed 1000/3934
Processed 1100/3934
Processed 1200/3934
Processed 1300/3934
Processed 1400/3934
Processed 1500/3934
Processed 1600/3934
Processed 1700/3934
Processed 1800/3934
Processed 1900/3934
Processed 2000/3934
Processed 2100/3934
Processed 2200/3934
Processed 2300/3934
Processed 2400/3934
Processed 2500/3934
Processed 2600/3934
Processed 2700/3934
Processed 2800/3934
Processed 2900/3934
Processed 3000/3934
Processed 3100/3934
Processed 3200/3934
Processed 3300/3934
Processed 3400/3934
Processed 3500/3934
Processed 3600/3934
Processed 3700/3934
Processed 3800/3934
Processed 3900/3934
CoT prediction completed.

In [39]:
y_true = sentiment_df["label"].str.lower().str.strip()
y_pred = sentiment_df["cot_prediction"].str.lower().str.strip()

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)
kappa = cohen_kappa_score(y_true, y_pred)

print("CoT Results")
print("----------------------------")
print(f"Accuracy   : {accuracy:.4f}")
print(f"Precision  : {precision:.4f}")
print(f"Recall     : {recall:.4f}")
print(f"F1-Score   : {f1:.4f}")
print(f"Cohen Kappa: {kappa:.4f}")

CoT Results
----------------------------
Accuracy   : 0.0155
Precision  : 0.4810
Recall     : 0.0155
F1-Score   : 0.0300
Cohen Kappa: 0.0049